"""add_attendance_records_table

Revision ID: 2311d939a9b2
Revises: fd5f49f29253
Create Date: 2026-09-03 23:46:12.795597

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2311d939a9b2'
down_revision: str | Sequence[str] | None = 'fd5f49f29253'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
