"""add_comp_off_requests_table

Revision ID: 6ddbb498fd41
Revises: 2311d939a9b2
Create Date: 2026-09-05 12:47:05.067287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddbb498fd41'
down_revision: Union[str, Sequence[str], None] = '2311d939a9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp_off_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('worked_date', sa.Date(), nullable=False),
    sa.Column('credit_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('action_reason', sa.String(length=500), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_off_requests_id'), 'comp_off_requests', ['id'], unique=False)
    op.create_index('uq_employee_worked_date_compoff', 'comp_off_requests', ['employee_id', 'worked_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employee_worked_date_compoff', table_name='comp_off_requests')
    op.drop_index(op.f('ix_comp_off_requests_id'), table_name='comp_off_requests')
    op.drop_table('comp_off_requests')
    # ### end Alembic commands ###
