"""add organizations table and org_id fk columns

Revision ID: 7b7d8e8b2ca6
Revises: 4631e6f337f4
Create Date: 2026-09-20 16:52:56.653235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7d8e8b2ca6'
down_revision: Union[str, Sequence[str], None] = '4631e6f337f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), server_default='trial', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('attendance_records', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendance_records_organization_id'), 'attendance_records', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'attendance_records', 'organizations', ['organization_id'], ['id'])
    op.add_column('comp_off_requests', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comp_off_requests_organization_id'), 'comp_off_requests', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'comp_off_requests', 'organizations', ['organization_id'], ['id'])
    op.add_column('departments', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_active_department_name'), table_name='departments', postgresql_where='(is_active IS TRUE)')
    op.create_index('uq_active_department_name', 'departments', ['organization_id', 'name'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'organizations', ['organization_id'], ['id'])
    op.add_column('employees', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_active_employee_code'), table_name='employees', postgresql_where='(is_active IS TRUE)')
    op.create_index('uq_active_employee_code', 'employees', ['organization_id', 'employee_code'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.drop_index(op.f('uq_active_employee_email'), table_name='employees', postgresql_where='(is_active IS TRUE)')
    op.create_index('uq_active_employee_email', 'employees', ['organization_id', 'email'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'organizations', ['organization_id'], ['id'])
    op.add_column('leave_balances', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leave_balances_organization_id'), 'leave_balances', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'leave_balances', 'organizations', ['organization_id'], ['id'])
    op.add_column('leave_requests', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leave_requests_organization_id'), 'leave_requests', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'leave_requests', 'organizations', ['organization_id'], ['id'])
    op.add_column('leave_types', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_active_leave_type_name'), table_name='leave_types', postgresql_where='(is_active IS TRUE)')
    op.create_index('uq_active_leave_type_name', 'leave_types', ['organization_id', 'name'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('ix_leave_types_organization_id'), 'leave_types', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'leave_types', 'organizations', ['organization_id'], ['id'])
    op.add_column('payroll_records', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payroll_records_organization_id'), 'payroll_records', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'payroll_records', 'organizations', ['organization_id'], ['id'])
    op.add_column('salary_structures', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_salary_structures_employee_id'), 'salary_structures', type_='unique')
    op.create_index(op.f('ix_salary_structures_employee_id'), 'salary_structures', ['employee_id'], unique=True)
    op.create_index(op.f('ix_salary_structures_organization_id'), 'salary_structures', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'salary_structures', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_structures', type_='foreignkey')
    op.drop_index(op.f('ix_salary_structures_organization_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_employee_id'), table_name='salary_structures')
    op.create_unique_constraint(op.f('uq_salary_structures_employee_id'), 'salary_structures', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('salary_structures', 'organization_id')
    op.drop_constraint(None, 'payroll_records', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_records_organization_id'), table_name='payroll_records')
    op.drop_column('payroll_records', 'organization_id')
    op.drop_constraint(None, 'leave_types', type_='foreignkey')
    op.drop_index(op.f('ix_leave_types_organization_id'), table_name='leave_types')
    op.drop_index('uq_active_leave_type_name', table_name='leave_types', postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('uq_active_leave_type_name'), 'leave_types', ['name'], unique=True, postgresql_where='(is_active IS TRUE)')
    op.drop_column('leave_types', 'organization_id')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_index(op.f('ix_leave_requests_organization_id'), table_name='leave_requests')
    op.drop_column('leave_requests', 'organization_id')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_index(op.f('ix_leave_balances_organization_id'), table_name='leave_balances')
    op.drop_column('leave_balances', 'organization_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index('uq_active_employee_email', table_name='employees', postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('uq_active_employee_email'), 'employees', ['email'], unique=True, postgresql_where='(is_active IS TRUE)')
    op.drop_index('uq_active_employee_code', table_name='employees', postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('uq_active_employee_code'), 'employees', ['employee_code'], unique=True, postgresql_where='(is_active IS TRUE)')
    op.drop_column('employees', 'organization_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index('uq_active_department_name', table_name='departments', postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('uq_active_department_name'), 'departments', ['name'], unique=True, postgresql_where='(is_active IS TRUE)')
    op.drop_column('departments', 'organization_id')
    op.drop_constraint(None, 'comp_off_requests', type_='foreignkey')
    op.drop_index(op.f('ix_comp_off_requests_organization_id'), table_name='comp_off_requests')
    op.drop_column('comp_off_requests', 'organization_id')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_records_organization_id'), table_name='attendance_records')
    op.drop_column('attendance_records', 'organization_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
