"""add_partial_unique_indexes_for_soft_deletes

Revision ID: 8b953a437d51
Revises: 75428ee96733
Create Date: 2026-08-30 12:01:36.899997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b953a437d51'
down_revision: Union[str, Sequence[str], None] = '75428ee96733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_name_key'), 'departments', type_='unique')
    op.create_index('uq_active_department_name', 'departments', ['name'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.create_index('uq_active_employee_code', 'employees', ['employee_code'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_index('uq_active_employee_email', 'employees', ['email'], unique=True, postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_employee_email', table_name='employees', postgresql_where=sa.text('is_active IS true'))
    op.drop_index('uq_active_employee_code', table_name='employees', postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.drop_index('uq_active_department_name', table_name='departments', postgresql_where=sa.text('is_active IS true'))
    op.create_unique_constraint(op.f('departments_name_key'), 'departments', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
