"""add_manager_and_employment_lifecycle_to_employees

Revision ID: ae3bb330b6c4
Revises: 8b953a437d51
Create Date: 2026-08-30 14:33:45.698237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3bb330b6c4'
down_revision: Union[str, Sequence[str], None] = '8b953a437d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employment_status', sa.String(length=50), server_default='active', nullable=False))
    op.add_column('employees', sa.Column('termination_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    op.drop_column('employees', 'termination_date')
    op.drop_column('employees', 'employment_status')
    # ### end Alembic commands ###
