"""create_salary_structure_and_payroll_tables

Revision ID: cf24005732de
Revises: 6ddbb498fd41
Create Date: 2026-09-06 23:54:23.767788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf24005732de'
down_revision: Union[str, Sequence[str], None] = '6ddbb498fd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_days_in_month', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('half_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('paid_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unpaid_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weekend_days', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lop_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_employee_payroll_month')
    )
    op.create_index(op.f('ix_payroll_records_employee_id'), 'payroll_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('special_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    # ### end Alembic commands ###
