"""add role field

Revision ID: dba466600e68
Revises: b64bb84de055
Create Date: 2026-03-23 20:00:52.218790

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dba466600e68'
down_revision: str | Sequence[str] | None = 'b64bb84de055'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
