"""add_attendance_records_table

Revision ID: fd5f49f29253
Revises: 70b7801917c8
Create Date: 2026-09-03 23:44:33.098752

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fd5f49f29253'
down_revision: str | Sequence[str] | None = '70b7801917c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
